// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdGeFntc9XKYC00yIyQkzlSKKS7MO7k5Q',
    appId: '1:482509291114:android:d23682202411cef728d413',
    messagingSenderId: '482509291114',
    projectId: 'flutter-chat-app-1e934',
    storageBucket: 'flutter-chat-app-1e934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP7pLRC4kYRGpEuOme4_2N7u1Mma3a3Pk',
    appId: '1:482509291114:ios:30c480762205971f28d413',
    messagingSenderId: '482509291114',
    projectId: 'flutter-chat-app-1e934',
    storageBucket: 'flutter-chat-app-1e934.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMo2Hb6iFLIzzzNpdLLjKGRbVecYIz0ag',
    appId: '1:482509291114:web:8e59259c29644a6f28d413',
    messagingSenderId: '482509291114',
    projectId: 'flutter-chat-app-1e934',
    authDomain: 'flutter-chat-app-1e934.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1e934.appspot.com',
  );

}